name: golangci-lint
'on':
  'push':
    'tags':
      - 'v*'
    'branches':
      - '*'
  'pull_request':

jobs:
  golangci:
    runs-on:
      ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          # This field is required.  Dont set the patch version to always use
          # the latest patch version.
          version: 1.64.7
